FROM node:24

WORKDIR /app

RUN npm install -g pnpm

COPY pnpm-workspace.yaml ./
COPY pnpm-lock.yaml ./
COPY package.json ./

COPY shared ./shared
COPY frontend ./frontend

RUN pnpm install

WORKDIR /app/frontend

ENV NODE_OPTIONS=--preserve-symlinks

CMD ["pnpm", "dev"]