name: viernulvier-archief
services:
  db:
    container_name: viernulvier-db
    image: postgres:18
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - database-data:/var/lib/postgresql
    networks:
      - viernulvier-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
  backend:
    env_file:
      - .env
    container_name: viernulvier-backend
    restart: always
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
    networks:
      - viernulvier-network
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
  frontend:
    env_file:
      - .env
    restart: always
    tty: true
    networks:
      - viernulvier-network
    container_name: viernulvier-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
volumes:
  database-data:
    external: false
    name: viernulvier-database-data
networks:
  viernulvier-network:
    driver: bridge
