FROM node:24

WORKDIR /app

RUN npm install -g pnpm

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json .npmrc ./

COPY shared/package.json ./shared/
COPY backend/package.json ./backend/

RUN pnpm install --frozen-lockfile

WORKDIR /app/backend

CMD ["pnpm", "dev"]
