FROM node:24

WORKDIR /app

RUN npm install -g pnpm

COPY pnpm-workspace.yaml ./
COPY pnpm-lock.yaml ./
COPY package.json ./

COPY shared/package.json ./shared/
COPY backend/package.json ./backend/

RUN pnpm install --frozen-lockfile

COPY shared ./shared
COPY backend ./backend

WORKDIR /app/backend

ENV NODE_OPTIONS=--preserve-symlinks

CMD ["pnpm", "dev"]
