-- UNDER NO CIRCUMSTANCES MAY THIS FILE BE EDITED WHEN LIVE
-- ANY EDITS WILL RESOLVE IN DIFFEREN CHECKSUMS AND THE DB REJECTING THE MIGRATION

-- 002.undo.create-hall-table.sql
-- Reverses 002.do.create-hall-table.sql.

DROP TABLE IF EXISTS hall;
