-- UNDER NO CIRCUMSTANCES MAY THIS FILE BE EDITED WHEN LIVE
-- ANY EDITS WILL RESOLVE IN DIFFERENT CHECKSUMS AND THE DB REJECTING THE MIGRATION

-- Drops tag and tag_type tables
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS tag_type;