-- UNDER NO CIRCUMSTANCES MAY THIS FILE BE EDITED WHEN LIVE
-- ANY EDITS WILL RESOLVE IN DIFFERENT CHECKSUMS AND THE DB REJECTING THE MIGRATION

-- Drops image and crop tables
DROP TABLE IF EXISTS image;
DROP TABLE IF EXISTS crop;
