-- UNDER NO CIRCUMSTANCES MAY THIS FILE BE EDITED WHEN LIVE
-- ANY EDITS WILL RESOLVE IN DIFFERENT CHECKSUMS AND THE DB REJECTING THE MIGRATION

-- Drops blogpost and blog tables
DROP TABLE IF EXISTS blogpost;
DROP TABLE IF EXISTS blog;