-- UNDER NO CIRCUMSTANCES MAY THIS FILE BE EDITED WHEN LIVE
-- ANY EDITS WILL RESOLVE IN DIFFERENT CHECKSUMS AND THE DB REJECTING THE MIGRATION

-- Drops the custom field tables
DROP TABLE IF EXISTS production_custom_field;
DROP TABLE IF EXISTS custom_production_field_definition;