-- UNDER NO CIRCUMSTANCES MAY THIS FILE BE EDITED WHEN LIVE
-- ANY EDITS WILL RESOLVE IN DIFFERENT CHECKSUMS AND THE DB REJECTING THE MIGRATION

-- 008.undo.alter-event-doors-at-to-timestamptz.sql
-- Revert event.doors_at to VARCHAR(64).

ALTER TABLE event
  ALTER COLUMN doors_at TYPE VARCHAR(64)
  USING doors_at::TEXT;
