-- UNDER NO CIRCUMSTANCES MAY THIS FILE BE EDITED WHEN LIVE
-- ANY EDITS WILL RESOLVE IN DIFFERENT CHECKSUMS AND THE DB REJECTING THE MIGRATION

-- Removes the old_id column from the specified tables.

ALTER TABLE production
DROP COLUMN IF EXISTS old_id;

ALTER TABLE event 
DROP COLUMN IF EXISTS old_id;

ALTER TABLE event_price
DROP COLUMN IF EXISTS old_id;

ALTER TABLE tag
DROP COLUMN IF EXISTS old_id;

ALTER TABLE hall 
DROP COLUMN IF EXISTS old_id;

ALTER TABLE image 
DROP COLUMN IF EXISTS old_id;

ALTER TABLE crop 
DROP COLUMN IF EXISTS old_id;