-- UNDER NO CIRCUMSTANCES MAY THIS FILE BE EDITED WHEN LIVE
-- ANY EDITS WILL RESOLVE IN DIFFERENT CHECKSUMS AND THE DB REJECTING THE MIGRATION

-- Adds an old_id column, representing the id from the website we scrape.

ALTER TABLE production
ADD COLUMN old_id INT UNIQUE;

ALTER TABLE event 
ADD COLUMN old_id INT UNIQUE;

ALTER TABLE event_price
ADD COLUMN old_id INT UNIQUE;

ALTER TABLE tag
ADD COLUMN old_id INT UNIQUE;

ALTER TABLE hall 
ADD COLUMN old_id INT UNIQUE;

ALTER TABLE image 
ADD COLUMN old_id INT UNIQUE;

ALTER TABLE crop 
ADD COLUMN old_id INT UNIQUE;