-- UNDER NO CIRCUMSTANCES MAY THIS FILE BE EDITED WHEN LIVE
-- ANY EDITS WILL RESOLVE IN DIFFERENT CHECKSUMS AND THE DB REJECTING THE MIGRATION

-- Restore the UNIQUE constraint on blogpost.blog.
ALTER TABLE blogpost ADD CONSTRAINT blogpost_blog_key UNIQUE (blog);
