-- UNDER NO CIRCUMSTANCES MAY THIS FILE BE EDITED WHEN LIVE
-- ANY EDITS WILL RESOLVE IN DIFFERENT CHECKSUMS AND THE DB REJECTING THE MIGRATION

-- Drops legacy hall.space (JSONB); not exposed in API or shared HallSchema.

ALTER TABLE hall
  DROP COLUMN space;
