-- UNDER NO CIRCUMSTANCES MAY THIS FILE BE EDITED WHEN LIVE
-- ANY EDITS WILL RESOLVE IN DIFFERENT CHECKSUMS AND THE DB REJECTING THE MIGRATION

-- Convert JSONB back to VARCHAR/TEXT

ALTER TABLE blog
  ALTER COLUMN name TYPE VARCHAR(64) USING (name->>'nl'),
  ALTER COLUMN name DROP DEFAULT,
  
  ALTER COLUMN description TYPE TEXT USING (description->>'nl');

ALTER TABLE blogpost 
  ALTER COLUMN title TYPE VARCHAR(255) USING (title->>'nl'),
  ALTER COLUMN title DROP DEFAULT;