import z from "zod";

import { EventPriceSchema } from "@viernulvier/shared/index.js";

// For creation, we exclude the id field since it's generated by the database
export const EventPriceCreateSchema = EventPriceSchema.omit({ id: true });
export type EventPriceCreate = z.infer<typeof EventPriceCreateSchema>;