import z from "zod";

import { EventPriceSchema } from "@viernulvier/shared/index.js";
import type { FastifyInstance } from "fastify";
import { buildQuery } from "@/routes/helpers.js";

// For creation, we exclude the id field since it's generated by the database
export const EventPriceCreateSchema = EventPriceSchema.omit({ id: true });
export type EventPriceCreate = z.infer<typeof EventPriceCreateSchema>;

export function updateEventPrice(server: FastifyInstance) {
  return buildQuery(
    server,
    `UPDATE event_price
    SET event = $1, amount = $2, updated_at = $3, updated_by = $4
    WHERE id = $5
    RETURNING id, event, amount`,
    z.tuple([
      EventPriceCreateSchema.shape.event,
      EventPriceCreateSchema.shape.amount,
      z.date(),
      z.number().nonnegative(),
      z.number().nonnegative(),
    ]),
    EventPriceSchema,
  );
}