import z from "zod";

import { EventSchema, EventSchemaWithoutPrice, serial } from "@viernulvier/shared/index.js";
import { buildQuery } from "@/routes/helpers.js";
import type { FastifyInstance } from "fastify";

// For creation, we exclude the id field since it's generated by the database
export const EventCreateSchema = EventSchemaWithoutPrice.omit({ id: true });
export type EventCreate = z.infer<typeof EventCreateSchema>;

// Any input value that can be accepted as a date.
const DateTypeAny = z.union([z.string(), z.date()]).optional();




const EventBulkUpdateOutputSchema = EventCreateSchema.partial().extend({
  ids: z.array(serial()).nonempty(),
  starts_at: z.date().optional(),
  doors_at: z.date().optional().nullable(),
  ends_at:  z.date().optional().nullable(),
});

type EventBulkUpdateOutput = z.infer<typeof EventBulkUpdateOutputSchema>

// We override the date fields to the accepted inputs.
const EventBulkUpdateInputSchema = EventBulkUpdateOutputSchema.extend({
  starts_at: DateTypeAny,
  doors_at: DateTypeAny.nullable(),
  ends_at: DateTypeAny.nullable(),
});

type EventBulkUpdateInput =  z.infer<typeof EventBulkUpdateInputSchema>

/**
 * Normalizes date fields on event create/replace/edit payloads to `Date` instances.
 *
 * Treats `undefined` as “omit”, `null` as explicit null (for nullable `ends_at` / `doors_at`),
 * and invalid date strings as `undefined`. Non-object inputs are returned unchanged.
 *
 * Used for POST, PUT, PATCH, and bulk-edit handlers after JSON parsing.
 *
 * @param value - The value to normalize, typically a partial event object
 * @returns The normalized object with provided date fields converted to Date instances,
 *          undefined fields preserved as undefined, or the original value if not an object
 *
 * @example
 * const partialEvent = \{
 *   starts_at: "2026-02-01T18:00:00.000Z",
 *   production: 20
 *   // ends_at and doors_at are not provided
 * \};
 * const normalized = normalizePartialEventDates(partialEvent);
 * // normalized.starts_at is a Date object
 * // normalized.ends_at is undefined (not provided)
 * // normalized.doors_at is undefined (not provided)
 */
export function normalizePartialEventDates(value: EventBulkUpdateInput): EventBulkUpdateOutput
export function normalizePartialEventDates<T>(value: T): T
export function normalizePartialEventDates<T>(value: EventBulkUpdateInput | T): EventBulkUpdateOutput | T {
  if (!value || typeof value !== "object") return value;

  value = value as EventBulkUpdateInput;

  function parseDate(dateValue: z.infer<typeof DateTypeAny>): Date | undefined
  function parseDate(dateValue: z.infer<z.ZodNullable<typeof DateTypeAny>>): Date | undefined | null
  function parseDate(dateValue: z.infer<z.ZodNullable<typeof DateTypeAny>>) {
    if (dateValue === undefined ) {
      return undefined;
    }
    if (dateValue === null) {
      return null;
    }
    if (dateValue instanceof Date) {
      return dateValue;
    }
    const parsed = new Date(String(dateValue));
    // Return undefined if the date is invalid instead of an Invalid Date object
    return isNaN(parsed.getTime()) ? undefined : parsed;
  };

  return {
    ...value,
    starts_at: parseDate(value["starts_at"]),
    ends_at: parseDate(value["ends_at"]),
    doors_at: parseDate(value["doors_at"]),
  };
}

export const EventBulkUpdateSchema = z.codec(
  EventBulkUpdateInputSchema,
  EventBulkUpdateOutputSchema,
  {
    decode: normalizePartialEventDates,
    /* c8 ignore next */
    encode: (v) => v,
  },
)



export const selectPriceSubquery = `(SELECT COALESCE(ARRAY_AGG(ep.id), '{}') FROM event_price ep WHERE ep.event = event.id) AS price`;

export function updateEvent(server: FastifyInstance) {
  return buildQuery(
    server,
    `UPDATE event
    SET old_id = $1, starts_at = $2, ends_at = $3, production = $4, hall = $5, doors_at = $6, info = $7,
        updated_at = $8, updated_by = $9
    WHERE id = $10
    RETURNING id, old_id, starts_at, ends_at, production, hall, doors_at, info, ${selectPriceSubquery}`,
    z.tuple([
      EventCreateSchema.shape.old_id,
      EventCreateSchema.shape.starts_at,
      EventCreateSchema.shape.ends_at,
      EventCreateSchema.shape.production,
      EventCreateSchema.shape.hall,
      EventCreateSchema.shape.doors_at,
      EventCreateSchema.shape.info,
      z.date(),
      serial(),
      serial(),
    ]),
    EventSchema,
  )};